### ISSUE TITLE
Пожелание

### ISSUE THREAD

**Issue by WDIlsb** [fakemancat/vk-io-question#5]
Отличный модуль, но очень не хватает прерывания

Да, есть возможность установить лимит, но эту  возможность и так можно было организовать , используя параметр времени ответа

Но что если пользователь не будет отвечать вообще, хотелось бы прервать выполнение функции, выбросить его на другой уровень, изначальное меню, чтобы можно было удобно "Вы так и не дали ответ, игра закончена, вот меню"

А самое главное сделать это универсальным, чтобы не приходилось во всех местах после context.question отдельно прописывать конструкцию возврата в общее меню

**Comment by fakemancat** [comment]
Свяжись со мной в ВК https://vk.me/bryuhanovdima
Как раз разрабатываю новую бету, можно подумать над новыми функциями
