### ISSUE TITLE
Missing repo license

### ISSUE THREAD

**Issue by Viiprogrammer** [fakemancat/vk-io-question#9]
Repository doesn't contain a license file.

If the project is published without a license, then by default, all rights to the code remain the property of the author (All rights reserved).

**Comment by fakemancat** [comment]
Which license should be used then?

**Comment by Viiprogrammer** [comment]
> Which license should be used then?

The author decides for himself, but often it is MIT / Apache / GPL

https://choosealicense.com/appendix/

**Comment by fakemancat** [comment]
OK. I will use MIT. Thanks!
